spring.datasource.url=jdbc:postgresql://dpg-d74j4fhaae7s73bi7ksg-a:5432/mydatabase_pj4s
spring.datasource.username=myuser
spring.datasource.password=mVppWg2KrdEUWjgUeu5yMWv6388ySRwG




spring.sql.init.mode=always

spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql

spring.docker.compose.enabled=false



frontend.url =